name: game_day_valet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1+4

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  app_links: ^6.4.1
  bottom_sheet: ^4.0.4
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  dotted_line: ^3.2.3
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  floating_chat_button: ^1.1.0
  flutter:
    sdk: flutter
  flutter_chat_core: ^0.0.9
  flutter_chat_ui: ^1.6.15
  flutter_dotenv: ^5.2.1
  flutter_html: ^3.0.0
  flutter_local_notifications: ^19.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  http: ^1.4.0
  iconsax_plus: ^1.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^1.4.0
  lottie: ^3.3.1
  overlay_support: ^2.1.0
  pinput: ^5.0.1
  pusher_channels_flutter: ^2.4.0
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/gdv_logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/logo/
    - assets/lottie/
