// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGCNaQjyFHzcZ4MBOwvgrYv48QK0YiAag',
    appId: '1:222515758866:android:fbc7270418b63c247bd5cb',
    messagingSenderId: '222515758866',
    projectId: 'game-day-valet-gdv',
    storageBucket: 'game-day-valet-gdv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgDFyOwwXckuc-Hy1s5RufBZ5xSoABfiI',
    appId: '1:222515758866:ios:a9e76eae8c6424c07bd5cb',
    messagingSenderId: '222515758866',
    projectId: 'game-day-valet-gdv',
    storageBucket: 'game-day-valet-gdv.firebasestorage.app',
    androidClientId: '222515758866-linosllsubbu2o54kfrq95t248ji7bdr.apps.googleusercontent.com',
    iosClientId: '222515758866-okrdr27ktvcpmc92sgma4m5prvkjagqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameDayValet',
  );
}
